Repository HackSlashNITP/Cura, pull requests merged in 2023-10, with the labels that each got.

#3 Bug fixes
  android/build.gradle
  ios/Flutter/Debug.xcconfig
  ios/Flutter/Release.xcconfig
  ios/Podfile
  lib/individual/donation_page.dart
  lib/individual/health.dart
  lib/individual/spend_time.dart
  lib/individual/user_chat_screen.dart
  lib/individual/user_chats_menu.dart
  lib/organization/org_chat_screen.dart
  lib/organization/org_chats_menu.dart
  lib/shared/services/firebase_database.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/Flutter-Debug.xcconfig
  macos/Flutter/Flutter-Release.xcconfig
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/Podfile
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: bug, urgent, hacktoberfest, hacktoberfest-accepted

#9 UI of post feed enhanced
  lib/organization/postfeed.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 Fixed the pixel overflow
  lib/individual/donation_page.dart
  lib/individual/donor_details.dart
  lib/individual/health.dart
  lib/individual/home_page_individual.dart
  lib/individual/spend_time.dart
  lib/individual/user_chat_screen.dart
  lib/individual/user_chats_menu.dart
  lib/main.dart
  lib/organization/org_chat_screen.dart
  lib/shared/services/firebase_database.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: bug, hacktoberfest, hacktoberfest-accepted

#16 UI enhancement of Chat Screen
  lib/individual/home_page_individual.dart
  lib/individual/user_chat_screen.dart
  lib/individual/user_chats_menu.dart
  windows/flutter/generated_plugin_registrant.cc
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 Made changes to UI of the Spend Time Screen
  lib/individual/spend_time.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#18 Resolved the issue #14
  lib/individual/home_page_individual.dart
Labels: enhancement, hacktoberfest, hacktoberfest-accepted
